## How to get a matrix with border 1 and rest 0?

In [3]:
import numpy as np

n= int(input())
x = np.ones((n,n), dtype = int)


x[1:-1,1:-1] = 0
print(x)

5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
