## Getting the borders of a 2D numpy array

In [20]:
input_list = [[11, 12, 13, 14],
              [21, 22, 23, 24],
              [31, 32, 33, 34]]

import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing

x = array_2d.shape

col_first = array_2d[:,0]
row_first = array_2d[0,:]
col_last = array_2d[:,x[1]-1]
row_last = array_2d[x[0]-1]

print(col_first) 
print(row_first) 
print(col_last) 
print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]
