## How to get a plus sign in terms of 1?

In [5]:
n = int(input())
import numpy as np 
arr = np.zeros((n, n), dtype = int)
arr[n//2, :] = 1
arr[: , n//2] = 1
print(arr)

5
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
